language: ruby
rvm:
 - 2.3.0
services:
  -postgresql
addons:
  firefox: "46.0"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
